import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    paddingTop: 40,
    paddingHorizontal: 12,
  },
  header: {
    marginBottom: 8,
  },
  appTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#D4AF37',
  },
  headerSub: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 2,
  },
  timeBadge: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  timeBadgeText: {
    fontSize: 11,
    color: '#D4AF37',
    fontWeight: '600',
  },
  tabRow: {
    flexDirection: 'row',
    marginBottom: 8,
    borderRadius: 999,
    backgroundColor: '#1a1a1a',
    padding: 2,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 999,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#D4AF37',
  },
  tabButtonText: {
    fontSize: 12,
    color: '#9ca3af',
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: '#1a1a1a',
  },

  urgeButton: {
    backgroundColor: '#D4AF37',
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 4,
  },
  urgeText: {
    color: '#1a1a1a',
    fontWeight: '800',
  },
  caption: {
    fontSize: 11,
    color: '#9ca3af',
    marginBottom: 8,
  },
  summonBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
    backgroundColor: '#000000',
  },
  summonTitle: {
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 4,
  },
  summonText: {
    fontSize: 12,
    color: '#9ca3af',
  },

  modeRow: {
    flexDirection: 'row',
    marginTop: 12,
    marginBottom: 4,
  },
  modeButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1e293b',
    alignItems: 'center',
    marginRight: 4,
  },
  modeButtonActive: {
    backgroundColor: '#1a1a1a',
  },
  modeButtonText: {
    fontSize: 12,
    color: '#9ca3af',
  },
  modeButtonTextActive: {
    color: '#e5e7eb',
    fontWeight: '700',
  },

  chatBox: {
    flex: 1,
    minHeight: 0,

    marginTop: 8,
    borderRadius: 16,
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#1e293b',
    padding: 8,
  },
  chatTitle: {
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 4,
  },
  messages: {
    flex: 1,
    marginBottom: 6,
  },
  bubble: {
    maxWidth: '88%',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 18,
    marginBottom: 6,
  },
  userBubble: {
    backgroundColor: '#1a1a1a',
    alignSelf: 'flex-end',
  },
  kingBubble: {
    backgroundColor: '#D4AF37',
    alignSelf: 'flex-start',
  },
  bubbleLabel: {
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 2,
    color: '#000000',
  },
  bubbleText: {
    fontSize: 16,
    lineHeight: 26,
    color: '#e5e7eb',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  input: {
    flex: 1,
    minHeight: 36,
    maxHeight: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 13,
    color: '#e5e7eb',
    marginRight: 4,
  },
  sendButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendText: {
    color: '#1a1a1a',
    fontWeight: '700',
    fontSize: 12,
  },
  privacyNote: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 4,
  },

  secondaryButton: {
    marginTop: 6,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4b5563',
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 11,
    color: '#e5e7eb',
  },

  historyInfo: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 4,
  },
  historyEntry: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#1f2937',
    padding: 8,
    marginBottom: 6,
    backgroundColor: '#000000',
  },
  historyDate: {
    fontSize: 11,
    color: '#9ca3af',
    marginBottom: 2,
  },
  historyLabel: {
    fontSize: 11,
    color: '#e5e7eb',
    marginTop: 4,
    fontWeight: '700',
  },
  historyText: {
    fontSize: 12,
    color: '#d1d5db',
  },

  goalCard: {
    borderRadius: 16,
    backgroundColor: '#000000',
    borderWidth: 1,
    borderColor: '#1e293b',
    padding: 12,
    marginTop: 8,
  },
  goalTitle: {
    fontSize: 16,
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 4,
  },
  goalSub: {
    fontSize: 12,
    color: '#9ca3af',
    marginBottom: 6,
  },
  bigInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 10,
    fontSize: 13,
    color: '#e5e7eb',
    minHeight: 56,
    marginTop: 4,
    marginBottom: 8,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  routineChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#334155',
    marginRight: 4,
    marginBottom: 4,
  },
  routineChipActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  routineChipText: {
    fontSize: 11,
    color: '#9ca3af',
  },
  routineChipTextActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },
  todoInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 8,
    fontSize: 13,
    color: '#e5e7eb',
    minHeight: 48,
  },

  primaryButton: {
    marginTop: 10,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#2DD4BF',
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#022c22',
    fontWeight: '800',
    fontSize: 13,
  },

  questionText: {
    fontSize: 13,
    color: '#e5e7eb',
    marginTop: 8,
  },

  progressBar: {
    width: '100%',
    height: 10,
    borderRadius: 999,
    backgroundColor: '#1a1a1a',
    overflow: 'hidden',
    marginTop: 6,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#D4AF37',
  },
  progressHint: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 4,
  },

  dateChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#374151',
    marginRight: 4,
  },
  dateChipActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  dateChipText: {
    fontSize: 11,
    color: '#9ca3af',
  },
  dateChipTextActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },

  todoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#6b7280',
    marginRight: 6,
  },
  checkboxChecked: {
    backgroundColor: '#2DD4BF',
    borderColor: '#2DD4BF',
  },
  todoText: {
    fontSize: 12,
    color: '#e5e7eb',
  },
  todoTextDone: {
    color: '#9ca3af',
    textDecorationLine: 'line-through',
  },

  historyButtonsRow: {
    flexDirection: 'row',
    marginTop: 8,
  },
  historyButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    alignItems: 'center',
    marginRight: 4,
  },
  historyDeleteButton: {
    backgroundColor: '#7f1d1d',
    marginLeft: 4,
    marginRight: 0,
  },
  historyButtonText: {
    fontSize: 12,
    color: '#e5e7eb',
    fontWeight: '600',
  },

  avatarCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 10,
    marginTop: 8,
  },
  avatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#1a1a1a',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  avatarEmoji: {
    fontSize: 28,
  },
  avatarInfo: {
    flex: 1,
  },
  avatarTitle: {
    fontSize: 14,
    color: '#e5e7eb',
    fontWeight: '700',
  },
  avatarRank: {
    fontSize: 12,
    color: '#D4AF37',
    marginTop: 2,
  },
  avatarDesc: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 2,
  },

  samuraiMissionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  samuraiMissionTitle: {
    fontSize: 14,
    color: '#e5e7eb',
    fontWeight: '700',
  },
  samuraiMissionXp: {
    fontSize: 11,
    color: '#facc15',
    fontWeight: '600',
  },
  samuraiMissionBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 10,
    marginTop: 4,
  },
  samuraiMissionText: {
    fontSize: 13,
    color: '#e5e7eb',
    marginBottom: 8,
  },
  samuraiMissionButton: {
    marginTop: 6,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#2DD4BF',
    alignItems: 'center',
  },
  samuraiMissionButtonText: {
    fontSize: 12,
    color: '#022c22',
    fontWeight: '700',
  },

  samuraiHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  samuraiHeaderTitle: {
    fontSize: 16,
    color: '#e5e7eb',
    fontWeight: '700',
  },
  samuraiEditButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#4b5563',
  },
  samuraiEditText: {
    fontSize: 11,
    color: '#e5e7eb',
  },

  onboardingLabel: {
    fontSize: 12,
    color: '#e5e7eb',
    marginTop: 8,
    marginBottom: 2,
  },
  onboardingInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 8,
    fontSize: 13,
    color: '#e5e7eb',
    minHeight: 48,
  },
  onboardingButton: {
    marginTop: 8,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#2DD4BF',
    alignItems: 'center',
  },
  onboardingButtonText: {
    fontSize: 13,
    color: '#022c22',
    fontWeight: '700',
  },
  samuraiHeaderLabel: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 6,
  },
  samuraiHeaderText: {
    fontSize: 13,
    color: '#e5e7eb',
    marginTop: 2,
  },

  urlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  urlInput: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 13,
    color: '#e5e7eb',
    marginRight: 4,
  },
  urlOpenButton: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#D4AF37',
    alignItems: 'center',
  },
  urlOpenButtonText: {
    fontSize: 12,
    color: '#1a1a1a',
    fontWeight: '700',
  },
  browserInfo: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 14,
    color: '#e5e7eb',
    fontWeight: '700',
    marginTop: 10,
  },

  blockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  blockDomain: {
    fontSize: 12,
    color: '#e5e7eb',
  },
  blockRemove: {
    fontSize: 11,
    color: '#D4AF37',
  },

  browserContainer: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#1f2937',
    marginTop: 8,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },

  blockedCard: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
  },
  blockedTitle: {
    fontSize: 16,
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 8,
  },
  blockedText: {
    fontSize: 13,
    color: '#d1d5db',
  },
  blockedButton: {
    marginTop: 12,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#D4AF37',
    alignItems: 'center',
  },
  blockedButtonText: {
    fontSize: 13,
    color: '#1a1a1a',
    fontWeight: '700',
  },

  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  settingsRowText: {
    flex: 1,
    marginRight: 8,
  },
  settingsLabel: {
    fontSize: 13,
    color: '#e5e7eb',
    fontWeight: '600',
  },
  settingsHint: {
    fontSize: 11,
    color: '#9ca3af',
    marginTop: 2,
  },

  segmentRow: {
    flexDirection: 'row',
    marginTop: 6,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#374151',
    paddingVertical: 6,
    alignItems: 'center',
    marginRight: 4,
  },
  segmentButtonActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  segmentButtonText: {
    fontSize: 12,
    color: '#9ca3af',
  },
  segmentButtonTextActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },

  timeInput: {
    width: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 6,
    paddingVertical: 4,
    fontSize: 13,
    color: '#e5e7eb',
    textAlign: 'center',
  },

  onboardingContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingTop: 12,
  },
  onboardingLead: {
    fontSize: 13,
    color: '#d1d5db',
    marginTop: 4,
    marginBottom: 8,
  },

  loadingContainer: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 8,
    fontSize: 13,
    color: '#e5e7eb',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    width: '100%',
    maxHeight: '80%',
    backgroundColor: '#000000',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#334155',
    padding: 14,
  },
  modalTitle: {
    fontSize: 16,
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 6,
  },
  modalText: {
    fontSize: 12,
    color: '#d1d5db',
  },

  timeOverContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeOverCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#4b5563',
    padding: 16,
    backgroundColor: '#000000',
    width: '100%',
  },
  timeOverTitle: {
    fontSize: 16,
    color: '#e5e7eb',
    fontWeight: '700',
    marginBottom: 8,
  },
  timeOverText: {
    fontSize: 13,
    color: '#d1d5db',
  },
  // スタート画面スタイル
  // Intro画面スタイル
  introScreen: {
    flex: 1,
    backgroundColor: '#000',
  },
  introVideo: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  introSkipButton: {
    position: 'absolute',
    bottom: 50,
    right: 24,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 77, 0.5)',
  },
  introSkipButtonText: {
    color: '#C9A24D',
    fontSize: 16,
    fontWeight: '600',
  },
  introBottomContainer: {
    position: 'absolute',
    bottom: 50,
    right: 24,
  },
  introHomeButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(201, 162, 77, 0.5)',
  },
  introHomeButtonText: {
    color: '#C9A24D',
    fontSize: 16,
    fontWeight: '600',
  },
  introScrollContent: {
    padding: 24,
    paddingTop: 60,
    paddingBottom: 40,
  },
  introTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#C9A24D',
    textAlign: 'center',
    marginBottom: 32,
    letterSpacing: 2,
  },
  introSection: {
    marginBottom: 20,
    paddingLeft: 8,
  },
  introSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#e5e7eb',
    marginBottom: 4,
  },
  introSectionText: {
    fontSize: 14,
    color: '#9ca3af',
    lineHeight: 20,
  },
  skipIntroCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 24,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#4b5563',
    borderRadius: 4,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#C9A24D',
    borderColor: '#C9A24D',
  },
  checkboxMark: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  skipIntroText: {
    fontSize: 14,
    color: '#9ca3af',
  },
  introButton: {
    backgroundColor: '#C9A24D',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  introButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
  },
  settingsButton: {
    backgroundColor: '#1e293b',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 16,
  },
  settingsButtonText: {
    fontSize: 14,
    color: '#C9A24D',
    textAlign: 'center',
  },
  dojoGateOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  dojoGateImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  dojoGateButtonContainer: {
    position: 'absolute',
    bottom: 120,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  dojoGateButton: {
    backgroundColor: 'rgba(201, 162, 77, 0.9)',
    paddingHorizontal: 48,
    paddingVertical: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#C9A24D',
  },
  dojoGateButtonText: {
    fontSize: 20,
    color: '#000',
    fontWeight: 'bold',
    letterSpacing: 4,
  },
  dojoGateTitle: {
    fontSize: 64,
    color: '#C9A24D',
    fontWeight: 'bold',
    letterSpacing: 16,
    marginBottom: 16,
  },
  dojoGateSubtitle: {
    fontSize: 16,
    color: '#C9A24D',
    opacity: 0.7,
    letterSpacing: 4,
  },
  startScreen: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  startTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#D4AF37',
    marginBottom: 8,
  },
  startQuote: {
    fontSize: 16,
    color: '#888',
    fontStyle: 'italic',
    marginBottom: 32,
  },
  startSubtitle: {
    fontSize: 20,
    color: '#FFF',
    marginBottom: 24,
  },
  startButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 12,
    paddingVertical: 18,
    paddingHorizontal: 32,
    marginVertical: 8,
    width: '100%',
    alignItems: 'center',
  },
  startButtonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: '600',
  },
  // トーストスタイル
  toastContainer: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    right: 20,
    backgroundColor: '#D4AF37',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    zIndex: 9999,
  },
  toastText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Paywallスタイル
  paywallOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  paywallCard: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    alignItems: 'center',
  },
  paywallTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 8,
  },
  paywallSubtitle: {
    fontSize: 14,
    color: '#888',
    marginBottom: 20,
    textAlign: 'center',
    lineHeight: 22,
  },
  paywallPrice: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#D4AF37',
    marginBottom: 24,
  },
  paywallButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 48,
    marginBottom: 12,
    width: '100%',
    alignItems: 'center',
  },
  paywallButtonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  paywallRestoreButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 48,
    marginBottom: 12,
    width: '100%',
    alignItems: 'center',
  },
  paywallRestoreText: {
    color: '#888',
    fontSize: 14,
  },
  paywallCloseText: {
    color: '#666',
    fontSize: 14,
    marginTop: 8,
  },
  // プラン選択スタイル
  planContainer: {
    width: '100%',
    marginBottom: 20,
  },
  planOption: {
    backgroundColor: '#2a2a3e',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
    position: 'relative',
  },
  planSelected: {
    borderColor: '#D4AF37',
    backgroundColor: '#2a2a4e',
  },
  planBadge: {
    position: 'absolute',
    top: -10,
    right: 12,
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  planBadgeText: {
    color: '#000',
    fontSize: 11,
    fontWeight: 'bold',
  },
  planName: {
    fontSize: 16,
    color: '#FFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  planPrice: {
    fontSize: 20,
    color: '#D4AF37',
    fontWeight: 'bold',
  },
  paywallLegal: {
    fontSize: 10,
    color: '#666',
    textAlign: 'center',
    marginTop: 16,
    lineHeight: 14,
    paddingHorizontal: 8,
  },
  paywallLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  paywallLinkText: {
    fontSize: 12,
    color: '#888',
    textDecorationLine: 'underline',
  },
  paywallLinkDivider: {
    fontSize: 12,
    color: '#666',
    marginHorizontal: 8,
  },
  // Proボタンスタイル
  proButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  proButtonText: {
    color: '#000',
    fontSize: 14,
    fontWeight: '700',
  },
  restoreButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    paddingVertical: 10,
    marginTop: 8,
    alignItems: 'center',
  },
  restoreButtonText: {
    color: '#888',
    fontSize: 13,
  },
  // 無効ボタンスタイル
  startButtonDisabled: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333',
  },
  startButtonTextDisabled: {
    color: '#555',
  },
  // 感謝スタイル
  gratitudeProgress: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#D4AF37',
    textAlign: 'center',
    marginVertical: 16,
  },
  gratitudeInput: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 16,
    color: '#FFF',
    fontSize: 16,
    marginBottom: 12,
  },
  gratitudeCompleteTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D4AF37',
    marginBottom: 12,
    textAlign: 'center',
  },
  gratitudeCompleteBox: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginVertical: 16,
  },
  gratitudeCompleteText: {
    color: '#D4AF37',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
  },
  gratitudeListContainer: {
    marginTop: 16,
  },
  gratitudeItem: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  gratitudeItemNumber: {
    color: '#D4AF37',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 8,
    width: 24,
  },
  gratitudeItemText: {
    color: '#e5e7eb',
    fontSize: 14,
    flex: 1,
  },
  quizButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  quizButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  proOnlyText: {
    color: '#666',
    fontSize: 14,
    marginTop: 8,
  },
  // クイズスタイル
  quizOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  quizCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    alignItems: 'center',
  },
  quizProgress: {
    color: '#D4AF37',
    fontSize: 14,
    marginBottom: 16,
  },
  quizQuestion: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 24,
  },
  quizInput: {
    backgroundColor: '#000',
    borderRadius: 12,
    padding: 16,
    color: '#FFF',
    fontSize: 18,
    textAlign: 'center',
    width: '100%',
    marginBottom: 12,
  },
  quizHint: {
    color: '#666',
    fontSize: 12,
    marginBottom: 16,
  },
  quizSubmitButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 48,
    marginBottom: 16,
  },
  quizSubmitText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  quizResultText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  quizCorrect: {
    color: '#2DD4BF',
  },
  quizWrong: {
    color: '#ef4444',
  },
  quizNextButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 48,
    marginBottom: 16,
  },
  quizNextText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  quizCloseText: {
    color: '#666',
    fontSize: 14,
    marginTop: 8,
  },
  // ホームボタン
  homeButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  homeButtonText: {
    fontSize: 12,
    color: '#D4AF37',
    fontWeight: '600',
  },
  // ヘッダーアイコン
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  // 道場タイトル
  dojoTitle: {
    fontSize: 18,
    color: '#D4AF37',
    fontWeight: '600',
    marginBottom: 8,
  },
  settingsIconButton: {
    position: 'absolute',
    top: 60,
    right: 24,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsIconText: {
    fontSize: 24,
  },
  // 集中機能スタイル
  focusQuestion: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D4AF37',
    textAlign: 'center',
    marginBottom: 8,
  },
  focusInput: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 16,
    color: '#FFF',
    fontSize: 16,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 16,
  },
  focusPurposeBar: {
    backgroundColor: '#1a1a1a',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#D4AF37',
  },
  focusPurposeLabel: {
    color: '#D4AF37',
    fontSize: 14,
  },
  blockedSitesSection: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
  },
  blockedSitesTitle: {
    color: '#D4AF37',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  blockedSiteItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  blockedSiteText: {
    color: '#e5e7eb',
    fontSize: 14,
  },
  removeSiteText: {
    color: '#ef4444',
    fontSize: 12,
  },
  addSiteRow: {
    flexDirection: 'row',
    marginTop: 12,
  },
  addSiteInput: {
    flex: 1,
    backgroundColor: '#000',
    borderRadius: 8,
    padding: 10,
    color: '#FFF',
    fontSize: 14,
    marginRight: 8,
  },
  addSiteButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  addSiteButtonText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  focusQBox: {
    backgroundColor: '#000',
    borderRadius: 12,
    padding: 20,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#D4AF37',
  },
  focusQText: {
    color: '#FFF',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '500',
  },
  // 集中モード選択
  focusTypeButton: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 20,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: '#333',
    alignItems: 'center',
  },
  focusTypeEmoji: {
    fontSize: 40,
    marginBottom: 8,
  },
  focusTypeButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  focusTypeButtonSub: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
  },
  // 勉強タイマー画面
  studyTimerScreen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  studyTimerLabel: {
    color: '#D4AF37',
    fontSize: 18,
    marginBottom: 16,
  },
  studyTimerDisplay: {
    color: '#FFF',
    fontSize: 80,
    fontWeight: 'bold',
    fontVariant: ['tabular-nums'],
  },
  studyTimerControls: {
    flexDirection: 'row',
    marginTop: 40,
    gap: 16,
  },
  studyControlButton: {
    backgroundColor: '#D4AF37',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
  },
  studyControlText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // タイマー設定
  timerSettingSection: {
    marginBottom: 16,
  },
  timerSettingLabel: {
    color: '#D4AF37',
    fontSize: 14,
    marginBottom: 8,
  },
  timerButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timerButton: {
    backgroundColor: '#1a1a1a',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333',
    flex: 1,
    marginHorizontal: 4,
  },
  timerButtonActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  timerButtonText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
  },
  timerButtonTextActive: {
    color: '#000',
    fontWeight: 'bold',
  },
  // ネットモードトップバー
  focusTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a1a1a',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  focusEndText: {
    color: '#ef4444',
    fontSize: 14,
    fontWeight: '600',
  },
  focusTimerBox: {
    backgroundColor: '#D4AF37',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  focusTimerText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    fontVariant: ['tabular-nums'],
  },
  focusTimerControl: {
    fontSize: 24,
  },
  // NGクイズ
  ngQuizTitle: {
    color: '#D4AF37',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  ngQuizSub: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 12,
  },
  ngQuizRemaining: {
    color: '#ef4444',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  focusTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a1a1a',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  focusTimerBox: {
    backgroundColor: '#D4AF37',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  focusTimerBreak: {
    backgroundColor: '#2DD4BF',
  },
  focusTimerText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  focusTimerControl: {
    fontSize: 24,
  },
  focusSessionsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0a0a0a',
    padding: 8,
    paddingHorizontal: 12,
  },
  focusSessionsText: {
    color: '#D4AF37',
    fontSize: 12,
  },
  focusEndText: {
    color: '#ef4444',
    fontSize: 14,
    fontWeight: '600',
  },
  timerSettingSection: {
    marginBottom: 16,
  },
  timerSettingLabel: {
    color: '#D4AF37',
    fontSize: 14,
    marginBottom: 8,
  },
  timerButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timerButton: {
    backgroundColor: '#1a1a1a',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#333',
    flex: 1,
    marginHorizontal: 4,
  },
  timerButtonActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  timerButtonText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
  },
  timerButtonTextActive: {
    color: '#000',
    fontWeight: 'bold',
  },
  focusHistorySection: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
  },
  focusHistoryTitle: {
    color: '#D4AF37',
    fontSize: 14,
    marginBottom: 8,
  },
  focusHistoryItem: {
    color: '#9ca3af',
    fontSize: 13,
    paddingVertical: 6,
  },
  dojoIcon: {
    width: 80,
    height: 80,
    borderRadius: 16,
    marginBottom: 16,
  },
  // 欲望可視化スタイル
  // 相談選択画面
  consultSelectBg: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  consultSelectContainer: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 50,
    paddingTop: 150,
  },
  consultTitleBox: {
    marginBottom: 40,
    alignItems: 'center',
  },
  consultTitle: {
    color: '#1a1a1a',
    fontSize: 20,
    fontWeight: '300',
    letterSpacing: 3,
  },
  consultSubtitle: {
    color: '#666',
    fontSize: 11,
    marginTop: 8,
    letterSpacing: 1,
  },
  consultSelectButton: {
    backgroundColor: 'transparent',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 4,
    marginBottom: 14,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#8B0000',
  },
  consultSelectButtonText: {
    color: '#8B0000',
    fontSize: 14,
    fontWeight: '500',
  },
  consultBackButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  consultBackButtonText: {
    color: '#C9A24D',
    fontSize: 14,
  },
  consultModeRow: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 8,
  },
  consultModeButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#333',
  },
  consultModeButtonActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  consultModeText: {
    color: '#9ca3af',
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '600',
  },
  consultModeTextActive: {
    color: '#000',
  },
  yokubouBox: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  yokubouTitle: {
    color: '#D4AF37',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  yokubouSub: {
    color: '#9ca3af',
    fontSize: 13,
    marginBottom: 16,
  },
  yokubouImagePicker: {
    width: '100%',
    height: 200,
    backgroundColor: '#262626',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#333',
    borderStyle: 'dashed',
  },
  yokubouImagePreview: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  yokubouImagePlaceholder: {
    color: '#666',
    fontSize: 14,
  },
  yokubouInput: {
    backgroundColor: '#262626',
    borderRadius: 8,
    padding: 12,
    color: '#FFF',
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  yokubouSubmitButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  yokubouSubmitText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  yokubouReplyBox: {
    backgroundColor: '#0d2818',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
    borderLeftWidth: 3,
    borderLeftColor: '#2DD4BF',
  },
  yokubouReplyLabel: {
    color: '#2DD4BF',
    fontSize: 12,
    marginBottom: 4,
  },
  yokubouReplyText: {
    color: '#FFF',
    fontSize: 15,
    lineHeight: 22,
  },
  yokubouSaveButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 6,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  yokubouSaveText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  yokubouSavedText: {
    color: '#2DD4BF',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 12,
  },
  yokubouResetButton: {
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  yokubouResetText: {
    color: '#666',
    fontSize: 14,
  },
  yokubouButtonRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  yokubouCameraButton: {
    flex: 1,
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  yokubouCameraButtonText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  yokubouGalleryButton: {
    flex: 1,
    backgroundColor: '#333',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  yokubouGalleryButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // 1日1善スタイル
  goodDeedImageButtons: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  goodDeedCameraBtn: {
    flex: 1,
    backgroundColor: '#D4AF37',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  goodDeedCameraBtnText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  goodDeedGalleryBtn: {
    flex: 1,
    backgroundColor: '#333',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  goodDeedGalleryBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  goodDeedImagePreviewContainer: {
    marginBottom: 12,
  },
  goodDeedImagePreview: {
    width: '100%',
    height: 150,
    borderRadius: 8,
  },
  goodDeedInput: {
    backgroundColor: '#262626',
    borderRadius: 8,
    padding: 12,
    color: '#FFF',
    fontSize: 14,
    minHeight: 60,
    textAlignVertical: 'top',
    marginBottom: 12,
  },
  goodDeedTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  goodDeedTagChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#262626',
    borderWidth: 1,
    borderColor: '#333',
  },
  goodDeedTagChipActive: {
    backgroundColor: '#D4AF37',
    borderColor: '#D4AF37',
  },
  goodDeedTagText: {
    color: '#9ca3af',
    fontSize: 12,
  },
  goodDeedTagTextActive: {
    color: '#000',
    fontWeight: 'bold',
  },
  goodDeedListContainer: {
    marginTop: 16,
  },
  goodDeedListTitle: {
    color: '#D4AF37',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  goodDeedItem: {
    flexDirection: 'row',
    backgroundColor: '#1a1a1a',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  goodDeedItemImage: {
    width: 50,
    height: 50,
    borderRadius: 6,
    marginRight: 12,
  },
  goodDeedItemContent: {
    flex: 1,
  },
  goodDeedItemText: {
    color: '#FFF',
    fontSize: 14,
  },
  goodDeedItemTag: {
    color: '#D4AF37',
    fontSize: 12,
    marginTop: 4,
  },
  // 履歴画像スタイル
  historyImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 12,
  },
  addToDiaryButton: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#2a2a2a',
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  addToDiaryButtonText: {
    color: '#D4AF37',
    fontSize: 12,
    fontWeight: '600',
  },
  goodDeedLogItem: {
    paddingVertical: 6,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#D4AF37',
    marginBottom: 6,
  },
  goodDeedLogText: {
    color: '#FFF',
    fontSize: 14,
  },
  saveReviewButton: {
    flex: 1,
    backgroundColor: '#2DD4BF',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginRight: 8,
  },
  saveReviewButtonText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Apple風ボタンスタイル
  appleMainButton: {
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  appleMainButtonText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '600',
  },
  appleEditButton: {
    backgroundColor: '#2c2c2e',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  appleEditButtonText: {
    color: '#007AFF',
    fontSize: 17,
    fontWeight: '600',
  },
  appleDeleteLink: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  appleDeleteLinkText: {
    color: '#FF3B30',
    fontSize: 15,
  },
  appleCancelLink: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  appleCancelLinkText: {
    color: '#007AFF',
    fontSize: 15,
  },
  // ミッションアラームスタイル
  missionAlarmContainer: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    padding: 24,
    justifyContent: 'center',
  },
  missionAlarmTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FF4444',
    textAlign: 'center',
    marginBottom: 8,
  },
  missionAlarmSubtitle: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    marginBottom: 24,
  },
  missionAlarmSection: {
    backgroundColor: '#2a2a3e',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  missionAlarmSectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 12,
  },
  missionQuizTimer: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FF4444',
    textAlign: 'center',
    marginBottom: 12,
  },
  missionQuizQuestion: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#D4AF37',
    textAlign: 'center',
    marginBottom: 16,
  },
  missionQuizInput: {
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    padding: 16,
    fontSize: 24,
    color: '#FFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  missionAlarmButton: {
    backgroundColor: '#2DD4BF',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  missionAlarmButtonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  missionAlarmSecondaryButton: {
    backgroundColor: '#2a2a3e',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  missionAlarmSecondaryText: {
    color: '#FFF',
    fontSize: 16,
  },
  missionAmnestyButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  missionAmnestyText: {
    color: '#888',
    fontSize: 14,
  },
  // ミッション提案スタイル
  missionProposalBox: {
    backgroundColor: '#2a2a3e',
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
    borderWidth: 2,
    borderColor: '#D4AF37',
  },
  missionProposalText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 26,
  },
  missionProposalHint: {
    color: '#888',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
  },
  // 新オンボーディングスタイル
  newOnboardingContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'space-between',
    paddingHorizontal: 32,
    paddingTop: 120,
    paddingBottom: 60,
  },
  newOnboardingContent: {
    flex: 1,
    justifyContent: 'center',
  },
  newOnboardingTitle: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 36,
    textAlign: 'left',
  },
  newOnboardingSubtext: {
    color: '#666',
    fontSize: 14,
    marginTop: 32,
    lineHeight: 22,
  },
  newOnboardingQuestion: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  newOnboardingButton: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
    minHeight: 56,
  },
  newOnboardingButtonText: {
    color: '#000',
    fontSize: 17,
    fontWeight: '600',
  },
  newOnboardingChoices: {
    gap: 16,
  },
  newOnboardingPrimaryChoice: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    paddingVertical: 20,
    paddingHorizontal: 24,
    minHeight: 80,
  },
  newOnboardingChoiceTitle: {
    color: '#000',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  newOnboardingChoiceSub: {
    color: '#666',
    fontSize: 13,
  },
  newOnboardingSecondaryChoice: {
    backgroundColor: 'transparent',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333',
    paddingVertical: 20,
    paddingHorizontal: 24,
    minHeight: 80,
  },
  newOnboardingChoiceTitle2: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  newOnboardingChoiceSub2: {
    color: '#888',
    fontSize: 13,
  },
  // 相談からミッション作成ボタン
  createMissionButton: {
    backgroundColor: '#D4AF37',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginVertical: 12,
    alignItems: 'center',
  },
  createMissionButtonText: {
    color: '#000',
    fontSize: 15,
    fontWeight: '600',
  },
});
